name: Build and Deploy
on:
  push:
    branches:
      - render

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package -DskipTests=true # Use o comando Maven apropriado para construir o projeto

      - name: Deploy to VPS
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_SERVER_DIY_COMPANY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "target/app-faz-feira.jar"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}

      - name: Run container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_SERVER_DIY_COMPANY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            CONTAINER_NAME="api-faz-feira"
            if [ "$(docker ps -a -q -f name=$CONTAINER_NAME)" ]; then
              echo "Parando e removendo o contêiner existente..."
              docker stop $CONTAINER_NAME
              docker rm $CONTAINER_NAME
            else
              echo "Nenhum contêiner com o nome $CONTAINER_NAME encontrado."
            fi