name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode -DskipTests package
      - name: Tests
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: false
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into Server
        uses: appleboy/ssh-action@master
        with:
          host: 195.35.42.54
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY_SERVER_DIY_COMPANY }}
          script: |
            # Execute o script de implantação no servidor
            /apps/deploys/faz-feira-dev/deploy.sh