name: Build and Deploy

on:
  push:
    branches:
      - render  # Defina a branch desejada

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package  # Use o comando Maven apropriado para construir o projeto

      - name: Deploy to Server
        run: scp -P 22 target/app-faz-feira.jar root@195.35.42.54:/root/deploys/faz-feira-dev/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_SERVER_DIY_COMPANY }}

